#ifndef Channels_h
#define Channels_h

#ifdef SINILINK
    // onboard relay control pin = 4
    #define CHANNEL_ONE_CONTROL_PIN 4
#else
    #define CHANNEL_ONE_CONTROL_PIN 5
#endif

#define CHANNEL_ONE_REST_ENDPOINT_PATH "/rest/channelOneState"  //restChannelEndPoint
#define CHANNEL_ONE_SOCKET_PATH "/ws/channelOneState"  // webSocketChannelEndPoint
#define CHANNEL_ONE_DEFAULT_NAME "Water Pump" //  defaultChannelName
#define CHANNEL_ONE_CONFIG_JSON_PATH "/config/channelOneState.json"  // channelJsonConfigPath
#define CHANNEL_ONE_HOME_ASSISTANT_ENTITY "channel_one"
#define CHANNEL_ONE_DEFAULT_CONTROL_RUN_EVERY 15.0f
#define CHANNEL_ONE_DEFAULT_CONTROL_OFF_AFTER 3.0f
#define CHANNEL_ONE_DEFAULT_CONTROL_START_TIME_HOUR 8
#define CHANNEL_ONE_DEFAULT_CONTROL_START_TIME_MINUTE 0
#define CHANNEL_ONE_DEFAULT_CONTROL_END_TIME_HOUR 16
#define CHANNEL_ONE_DEFAULT_CONTROL_END_TIME_MINUTE 0
#define CHANNEL_ONE_DEFAULT_ENABLED_STATE true
#define CHANNEL_ONE_DEFAULT_ENABLE_TIME_SPAN_SCHEDULE false
#define CHANNEL_ONE_DEFAULT_RANDOMIZE_SCHEDULE false
#define CHANNEL_ONE_DEFAULT_SPAN_TIME 0.0f
#define CHANNEL_ONE_DEFAULT_OVERRIDE_TIME 15.0f // override time in minutes
#define CHANNEL_ONE_DEFAULT_ENABLE_MINIMUM_RUN_TIME_SCHEDULE false

#endif

//#define  CHANNEL_TWO_CONTROL_PIN 4