language: python
python:
    - "3.8"

before_install:
  - nvm install 10.15.3
  - nvm use 10.15.3

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run -e esp12e -e node32s
